### ISSUE TITLE
unpublish npm package

### ISSUE THREAD

**Issue by firehist** [angular-translate/angular-translate-extractor#3]
Hey @joonhocho 
Is it possible to unpublish npm package.
I was re-writing all the stuff around `grunt-angular-translate` in splitted libraries:
https://github.com/Boulangerie/angular-translate-extractor
https://github.com/Boulangerie/grunt-angular-translate
https://github.com/Boulangerie/gulp-angular-translate

With some cool features and DevOps stuff:
- Travis
- Auto release
- etc...

**Comment by joonhocho** [comment]
Sorry, I just read this issue and I will do so when I get home.

**Comment by joonhocho** [comment]
I think it's already done by npm?

**Comment by firehist** [comment]
Nop I still seeing the package through NPM registry:
https://www.npmjs.com/package/angular-translate-extractor

**Comment by joonhocho** [comment]
It does not let me unpublish since it's older than 24hrs.
I just added you the npm package owner list.
